version: '3'

services:
  rem-be:
    container_name: rem-be:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/ec2-user/containers/rem-be/logs:/logs