version: '3'

services:
  rem_be:
    image: rem_be
    container_name: rem_be
    restart: unless-stopped
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/ec2-user/containers/rem-be/logs:/logs
