spring:
  datasource:
    url: jdbc:postgresql://aws.dianagrigore.com:5432/rem
    username: postgres
    password: example

logging:
  level:
    com:
      dianagrigore:
        root: DEBUG
        rem: DEBUG
